name: Go tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test-linux:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go: [ 1.22.x, 1.23.x, 1.24.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install libusb
        run: sudo apt-get install libusb-1.0-0-dev

      - name: Run tests
        env:
          SKIP_YUBIKEY_TESTS: "1"
        run: go test -race ./...

  test-macos:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go: [ 1.22.x, 1.23.x, 1.24.x ]
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        env:
          SKIP_YUBIKEY_TESTS: "1"
        run: go test -race ./...

  test-windows:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go: [1.22.x, 1.23.x, 1.24.x]
        os: [ windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Install libusb
        uses: msys2/setup-msys2@v2
        with:
          install: |-
            mingw64/mingw-w64-x86_64-libusb
            mingw64/mingw-w64-x86_64-pkg-config

      - run: echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run tests
        env:
          SKIP_YUBIKEY_TESTS: "1"
        run: go test -race ./...
